export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const GET_CONTACT_START = "GET_CONTACT_START";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILED = "GET_CONTACT_FAILED";
export const NO_CONTACTS_IN_DATABASE = "NO_CONTACTS_IN_DATABASE";

export const ADD_CONTACT_START = "ADD_CONTACT_START";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED";

export const DELETE_CONTACT_START = "DELETE_CONTACT_START";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILED = "DELETE_CONTACT_FAILED";
